=== lakony-droid/XML/College.dtd
<!ELEMENT college (students+,courses)>
<!ELEMENT students (fullName,regNo,DateofBirth)>
<!ELEMENT fullName (firstName,lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT regNo (#PCDATA)>
<!ELEMENT DateofBirth (#PCDATA)>
<!ELEMENT courses (course+)>
<!ELEMENT course (courseName,creditHours)>
<!ELEMENT courseName (#PCDATA)>
<!ELEMENT CreditHours (#PCDATA)>

=== lakony-droid/XML/College.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE college SYSTEM "College.dtd">
<college>
  <students>
    <fullName>
      <firstName>Emmanuek</firstName>
      <lastName>Chezegwa</lastName>
    </fullName>
    <regNo>U5599</regNo>
    <DateofBirth>05/05/2004</DateofBirth>
  </students>

  <courses>
  <course>
    <courseName>DSE</courseName>
    <courseName>BAAE</courseName>
    <creditHours>4</creditHours>
  </course>
  </courses>
</college>
