=== lakony-droid/XML/employees.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name, position, salary)>
<!ATTLIST employee 
    id ID #REQUIRED
    department (HR | IT | Finance | Marketing) #REQUIRED>

<!ELEMENT name (firstName, lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>

<!ELEMENT position (#PCDATA)>

<!ELEMENT salary (#PCDATA)>
<!ATTLIST salary 
    currency CDATA #REQUIRED>

=== lakony-droid/XML/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">

<employees>
    <employee id="emp_101" department="IT">
        <name>
            <firstName>Emmanuel</firstName>
            <lastName>Lakony</lastName>
        </name>
        <position>Systems Architect</position>
        <salary currency="USD">4500</salary>
    </employee>

    <employee id="emp_102" department="Finance">
        <name>
            <firstName>Princess</firstName>
            <lastName>Anati</lastName>
        </name>
        <position>Financial Analyst</position>
        <salary currency="UGX">5500000</salary>
    </employee>

    <employee id="emp_103" department="Marketing">
        <name>
            <firstName>Leah</firstName>
            <lastName>Kamwine</lastName>
        </name>
        <position>Content Strategist</position>
        <salary currency="KES">120000</salary>
    </employee>
</employees>
